// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi-8p3kQCLHPyb-JZ5PMMjpMzRY6p6EBc',
    appId: '1:656507828714:web:e329c17a973e813a7dda93',
    messagingSenderId: '656507828714',
    projectId: 'graduation-app-88f35',
    authDomain: 'graduation-app-88f35.firebaseapp.com',
    storageBucket: 'graduation-app-88f35.appspot.com',
    measurementId: 'G-1364P5E8R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw1uYSf8XHNWhk3vSggwumWhqBKHWcFDM',
    appId: '1:656507828714:android:acd113b1d265a81c7dda93',
    messagingSenderId: '656507828714',
    projectId: 'graduation-app-88f35',
    storageBucket: 'graduation-app-88f35.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMK8dGARMgdG_Qe7f9QEdGci9JtYyoGjs',
    appId: '1:656507828714:ios:ad3eca6accf37d1a7dda93',
    messagingSenderId: '656507828714',
    projectId: 'graduation-app-88f35',
    storageBucket: 'graduation-app-88f35.appspot.com',
    iosBundleId: 'com.example.graduationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMK8dGARMgdG_Qe7f9QEdGci9JtYyoGjs',
    appId: '1:656507828714:ios:743b90a0c9b7645c7dda93',
    messagingSenderId: '656507828714',
    projectId: 'graduation-app-88f35',
    storageBucket: 'graduation-app-88f35.appspot.com',
    iosBundleId: 'com.example.graduationApp.RunnerTests',
  );
}
